config/routes.rb
Rails.application.routes.draw do

  root to: "application#index"
  post "/contact",     to: "application#contact"
  get  "/sitemap.xml", to: "application#sitemap", format: "xml", as: :sitemap

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
  end

  def contact
    render js: if Google::Recaptcha.verify(params["g-recaptcha-response"])
      ApplicationMailer.lets_talk(params[:email], params[:message]).deliver_later
      <<~JS
        $("form#contact").addClass("thank-you");
        $("form#contact button").removeClass("fa-spin");
      JS
    else
      <<~JS
        $("form#contact").addClass("verify-failed").delay(2000).queue(function(){
          $(this).removeClass("verify-failed").dequeue();
        });
      JS
    end
  end

  def sitemap
    respond_to do |format|
      format.xml
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_id
    # controller namespace and action, ex:
    # Admin::UsersController => admin_users
    controller.controller_path.split('/').join('_')
  end

  def page_classes
    # controller name, current action, and request varient, ex:
    # (for Admin::UsersController#show w/ iphone variant) => "users show iphone"
    [controller.controller_name, controller.action_name, request.variant].flatten.join(" ").strip
  end

end

app/views/application/index.html.erb
<%= link_to 'OverWine.io', root_path, id: 'brand' %>

<section id="jumbotron">
  <div id="jumbotron-content-wrapper">
    <div>
      <h1>Relax. Let us build your next MVP.</h1>
      <p>With over 10 years of industry experience working with startups and small businesses alike, we can help get your idea off the ground and take it to the next level.</p>
    </div>
  </div>
  <div id="jumbotron-social">
    <div class="fb-like" data-href="https://overwine.io" data-layout="button" data-action="like" data-size="large" data-show-faces="false" data-share="true"></div>
    <%= link_to icon("fas", "flag", "Visit on FB"), 'https://www.facebook.com/overwine.io', id: "facebook-page-button", target: :blank %>
  </div>
  <%= link_to image_tag("arrow-down.svg"), '#', id: 'scroll-down' %>
  <%= video_tag ["/videos/675073365.mp4", "/videos/675073365.webm"], poster: image_path('675073365.jpg'), autoplay: true, loop: true, muted: true %>
</section>

<section id="who-we-are">
  <div class="container">
    <h2>Who We Are</h2>
    <p>
      We're a pair of full-stack engineers specializing in Ruby on Rails located in the San Francisco Bay Area. Although
      we both have full-time jobs in Silicon Valley, we also enjoy a little freelancing on the side which gives us a
      chance to explore new ideas and work across different industries.
    </p>
    <div class="profile-card">
      <figure class="jeff"></figure>
      <article>
        <h3>Jeff Miller</h3>
        <p>
          Jeff is Lead Engineer at <%= link_to 'Cognoa', 'https://www.cognoa.com', target: '_blank' %>, whose
          mission is to employ big data and machine learning to vastly improve early childhood detection of developmental
          disabilities including autism.
        </p>
        <ul>
          <li><%= link_to icon("fas", "home"), 'https://humani.se', target: '_blank' %></li>
          <li><%= link_to icon("fab", "github"), 'https://www.github.com/ibanez270dx', target: '_blank' %></li>
          <li><%= link_to icon("fab", "linkedin"), 'https://www.linkedin.com/in/ibanez270dx', target: '_blank' %></li>
          <li><%= link_to icon("fas", "envelope"), 'mailto:jeff@humani.se', target: '_blank' %></li>
        </ul>
      </article>
    </div>

    <div class="profile-card">
      <figure class="gianna"></figure>
      <article>
        <h3>Gianna Fusaro</h3>
        <p>
          Gianna is a Senior Software Engineer at <%= link_to 'Wurl', 'http://www.wurl.com', target: '_blank' %>, where she
          designs and develops the tools and infrastructure to distribute secure, high-quality video streaming services to devices
          around the world.
        </p>
        <ul>
          <li><%= link_to icon("fas", "home"), 'http://www.gianna.codes', target: '_blank' %></li>
          <li><%= link_to icon("fab", "github"), 'https://www.github.com/giannafusaro', target: '_blank' %></li>
          <li><%= link_to icon("fab", "linkedin"), 'https://www.linkedin.com/in/giannafusaro', target: '_blank' %></li>
          <li><%= link_to icon("fas", "envelope"), 'mailto:gianna@gianna.codes', target: '_blank' %></li>
        </ul>
      </article>
    </div>
  </div>
</section>

<section id="what-we-do">
  <div class="container">
    <h2>What We Do</h2>
    <p>
      Our process is simple -- we take care of the full-cycle of web application development from initial concept to deployment.
      This includes requirements elicitation, designing, coding, testing and devops services.
    </p>

    <ul id="services">
      <li>
        <%= image_tag('gifs/animat-pencil-color.gif') %>
        <h4>1. Gather Requirements</h4>
        <p>We work with you to distill your vision into a crystal-clear set of requirements and deliverables so we can build you the best possible product.</p>
      </li>
      <li>
        <%= image_tag('gifs/animat-responsive-color.gif') %>
        <h4>2. Prototype and Design</h4>
        <p>We ensure your MVP provides an intuitive and memorable experience while functioning seamlessly across all devices and platforms.</p>
      </li>
      <li>
        <%= image_tag('gifs/animat-diamond-color.gif') %>
        <h4>3. Code, Code, Code</h4>
        <p>Using industry-leading best practices, we build a rock-solid MVP that you can test with your target audience or even pitch directly to investors.</p>
      </li>
      <li>
        <%= image_tag('gifs/animat-rocket-color.gif') %>
        <h4>4. Launch!</h4>
        <p>Gain valuable insights while attracting investors, cofounders, and early employees with a working MVP deployed on scalable cloud-based hosting.</p>
      </li>
    </ul>
  </div>
</section>

<section id='our-projects'>
  <div class="container">
    <h2>Featured Projects</h2>

    <div class="project">
      <figure>
        <%= link_to image_tag('projects/superpups.png'), 'https://www.superpups.biz', target: '_blank' %>
      </figure>
      <div class="flex-wrapper">
        <article>
          <h3>SuperPups</h3>
          <p>
            Small business website for San Mateo based pet salon, SuperPups. Includes a custom photo gallery and
            custom content management system.
          </p>
          <%= link_to 'www.superpups.biz', '#', target: '_blank' %>
        </article>
      </div>
    </div>

    <div class="project">
      <figure>
        <%= link_to image_tag('projects/myprohero.png'), 'https://www.myprohero.com', target: '_blank' %>
      </figure>
      <div class="flex-wrapper">
        <article>
          <h3><%= image_tag "projects/scoolu-logo.png" %></h3>
          <div>
            Formerly MyProHero
          </div>
          <p>
            Web app for facilitating and recording live online coaching and mentoring sessions through Google Hangouts and YouTube.
          </p>
          <%= link_to 'www.scoolu.com', 'https://www.scoolu.com/', target: '_blank' %>
        </article>
      </div>
    </div>
  </div>
</section>

<section id="contact-us">
  <div class="container">
    <h1>Let's Talk</h1>
    <p>
      Get a free quote for web application design and development<br />
      <small>Don't worry, we hate spam too. We won't share your email with anyone.</small>
    </p>
    <%= form_tag contact_path, id: "contact", remote: true do %>
      <%= email_field_tag :email, nil, placeholder: "Your email address" %>
      <%= text_area_tag :message, nil, placeholder: "Give us a brief description of your project and we'll get back to you as soon as we can.", rows: 8 %>
      <div class="flex-container">
        <div class="g-recaptcha" data-sitekey="6LeZt0UUAAAAAMzo82yoKNJFvQGt9okRI3zj21Xt"></div><br />
        <%= button_tag "Send Message", data: { disable_with: icon("fas", "spinner", "Sending...", class: "fa-spin").html_safe } %>
      </div>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>OverWine.io | Relax. Let us build your next MVP.</title>

    <%= csrf_meta_tags %>
    <%= tag :meta, charset: "utf-8" %>

    <%= tag :meta, name: "viewport",    content: "width=device-width, initial-scale=1, shrink-to-fit=no" %>
    <%= tag :meta, name: "description", content: "With over 10 years of experience working with startups and small businesses alike, we'll get your idea off the ground and build a fully-functional MVP." %>
    <%= tag :meta, name: "author",      content: "OverWine.io" %>
    <%= tag :meta, name: "keywords",    content: "OverWine, web, development, design, consulting, app, application, rails, ruby, mvp, minimum, viable, product, minimum viable product, dev, devops" %>

    <%= tag :meta, property: "fb:app_id",       content: "1593796620709372" %>
    <%= tag :meta, property: "og:site_name",    content: "OverWine.io" %>
    <%= tag :meta, property: "og:url",          content: "https://#{request.host_with_port}" %>
    <%= tag :meta, property: "og:image",        content: image_url("social.jpg") %>
		<%= tag :meta, property: "og:title",        content: "OverWine.io | Relax. Let us build your next MVP." %>
    <%= tag :meta, property: "og:description",  content: "Top-tier web application design & development from the heart of Silicon Valley." %>
		<%= tag :meta, property: "og:type",         content: "website" %>
    <%= tag :meta, property: "og:locale",       content: "en_US" %>

    <%= tag :meta, name: "twitter:card",        content: "summary_large_image" %>
    <%= tag :meta, name: "twitter:title",       content: "OverWine.io | Relax. Let us build your next MVP." %>
    <%= tag :meta, name: "twitter:description", content: "Top-tier web application design & development from the heart of Silicon Valley." %>
    <%= tag :meta, name: "twitter:image",       content: image_url("social.jpg") %>

    <%= tag :link, rel: "canonical", href: "https://#{request.host_with_port}/" %>
    <%= tag :link, rel: "icon",      href: image_path("favicon.png"), type: "image/png" %>

    <%= stylesheet_link_tag 'application', media: 'all' %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-113875556-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-113875556-1');
      gtag('config', 'GA_TRACKING_ID', { 'link_attribution': true });  // Enable enhanced link attribution
    </script>

    <%= javascript_include_tag 'application' %>

    <script src='https://www.google.com/recaptcha/api.js'></script>
  </head>

  <body id="<%= page_id %>" class="<%= page_classes %>">
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '1593796620709372',
          xfbml      : true,
          version    : 'v2.12'
        });
        FB.AppEvents.logPageView();
        FB.Event.subscribe("xfbml.render", function(){
          document.querySelector("#facebook-page-button").style.visibility = "visible";
        });
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "https://connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>

    <%= yield %>

    <footer>
      <div class="flex-container">
        <h4>Everything is better OverWine.</h4>
        <ul>
          <li><%= link_to icon("fab", "facebook"), 'https://www.facebook.com/overwine.io', target: :blank %></li>
          <li><%= link_to icon("fab", "twitter"), 'https://twitter.com/intent/tweet?url=https://overwine.io', target: :blank %></li>
          <li><%= link_to icon("fab", "google-plus"), 'https://plus.google.com/share?url=https://overwine.io', target: :blank %></li>
        </ul>
        <small>copyright <%= Time.now.year %> OverWine.io</small>
      </div>
    </footer>
  </body>
</html>